package com.edigest.journalApp.repository;

import com.edigest.journalApp.entity.*;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Component;

@Component
public interface UserRepository extends MongoRepository<User,ObjectId> {
// The findByUserName method is not a built-in MongoDB function but rather a method automatically generated by Spring Data MongoDB based on the method naming convention. Here's how it works:
// Spring Data Repository Custom Queries

// Spring Data MongoDB allows you to define custom query methods simply by declaring them in your repository interface. These methods follow a specific naming convention, and Spring Data MongoDB translates them into the corresponding MongoDB queries.
    User findByUserName(String userName);
    User deleteByUserName(String username);
    User findByJournalEntry(JournalEntry journalEntry);
}
